const BUDGET_COMMON_LABELS = {
  CDL_BDG_PAGE_TITLE: ' Management Firm Budgets',
  CDL_BDG_PAGE_SUBTITLE: 'Create, manage, and review  budget submissions.',
  CDL_BDG_LIST_TITLE: 'Saved Budgets',
  CDL_BDG_NEW_BUTTON: 'New Budget',
  CDL_BDG_EMPTY_STATE: 'No budgets recorded yet. Create a new budget to get started.',
  CDL_BDG_TABLE_MANAGEMENT_FIRM: 'Management Firm',
  CDL_BDG_TABLE_BUDGET_PERIOD: 'Budget Period',
  CDL_BDG_TABLE_TOTAL_COST: 'Total Cost',
  CDL_BDG_TABLE_ACTIONS: 'Actions',
  CDL_BDG_STEP_DETAILS: 'Budget Details',
  CDL_BDG_STEP_DOCUMENTS: 'Documents',
  CDL_BDG_STEP_REVIEW: 'Review',
  CDL_BDG_SECTION_GENERAL: 'General Information',
  CDL_BDG_SECTION_SERVICE: 'Service Charge Group',
  CDL_BDG_SECTION_PERIOD: 'Budget Period',
  CDL_BDG_SECTION_CATEGORIZATION: 'Categorisation',
  CDL_BDG_SECTION_FINANCIALS: 'Financials',
  CDL_BDG_REVIEW_SUMMARY: 'Budget Summary',
  CDL_BDG_REVIEW_GENERAL: 'General Information',
  CDL_BDG_REVIEW_PERIOD: 'Budget Period',
  CDL_BDG_REVIEW_CATEGORIZATION: 'Categorisation',
  CDL_BDG_REVIEW_FINANCIALS: 'Financials',
  CDL_BDG_DOC_TITLE: 'Budget Documents',
  CDL_BDG_DOC_DESCRIPTION:
    'Upload budget-related documents to support this submission. You can skip this step if documents are not available yet.',
  CDL_BDG_DOC_SAVE_HEADING: 'Save budget details to upload documents.',
  CDL_BDG_DOC_SAVE_MESSAGE:
    'Please return to Step 1 and save the budget before uploading documents.',
} as const

export const BUDGET_MANAGEMENT_FIRM_LABELS = {
    'CDL_BDG_MANAGEMENT_FIRM_GROUP_ID': 'Management Firm Group ID', // Mandatory, Numeric (10,0)
    'CDL_BDG_MANAGEMENT_FIRM_GROUP_NAME': 'Management Firm Group Name', // Mandatory, Alphanumeric (50,0)
    'CDL_BDG_MANAGEMENT_FIRM_GROUP_LOCAL_NAME': 'Management Firm Group Local Name', // Mandatory, Alphanumeric (50,0)
    'CDL_BDG_MASTER_COMMUNITY_NAME': 'Master Community Name', // Mandatory, Alphanumeric (50,0)
    'CDL_BDG_MASTER_COMMUNITY_LOCAL_NAME': 'Master Community Local Name', // Mandatory, Alphanumeric (50,0)
    'CDL_BDG_MANAGEMENT_COMPANY_ID': 'Management Company ID', // Mandatory, Numeric (10,0)
    'CDL_BDG_MANAGEMENT_COMPANY_NAME': 'Management Company Name', // Mandatory, Alphanumeric (50,0)
    'CDL_BDG_MANAGEMENT_COMPANY_LOCAL_NAME': 'Management Company Local Name', // Mandatory, Alphanumeric (50,0)
    'CDL_BDG_PROPERTY_MANAGER_EMAIL': 'Property Manager Email', // Mandatory, Email
    'CDL_BDG_SERVICE_CHARGE_GROUP_ID': 'Service Charge Group ID', // Mandatory, Numeric (10,0)
    'CDL_BDG_SERVICE_CHARGE_GROUP_NAME': 'Service Charge Group Name', // Mandatory, Alphanumeric (50,0)
    'CDL_BDG_SERVICE_CHARGE_GROUP_LOCAL_NAME': 'Service Charge Group Local Name', // Mandatory, Alphanumeric (50,0)
    'CDL_BDG_BUDGET_PERIOD_CODE': 'Budget Period Code', // Mandatory, Alphanumeric (20,0)
    'CDL_BDG_BUDGET_PERIOD_TITLE': 'Budget Period Title', // Mandatory, Alphanumeric (100,0)
    'CDL_BDG_BUDGET_PERIOD_FROM': 'Budget Period From', // Mandatory, ISO Date string
    'CDL_BDG_BUDGET_PERIOD_TO': 'Budget Period To', // Mandatory, ISO Date string
    'CDL_BDG_CATEGORY_CODE': 'Category Code', // Mandatory, Alphanumeric (10,0)
    'CDL_BDG_CATEGORY_NAME': 'Category Name ', // Mandatory, Alphanumeric (50,0)
    'CDL_BDG_CATEGORY_LOCAL_NAME': 'Category Name (Local)', // Mandatory, Alphanumeric (50,0)
    'CDL_BDG_SUB_CATEGORY_CODE': 'Sub-Category Code', // Mandatory, Alphanumeric (10,0)
    'CDL_BDG_SUB_CATEGORY_NAME': 'Sub-Category Name ', // Mandatory, Alphanumeric (50,0)
    'CDL_BDG_SUB_CATEGORY_LOCAL_NAME': 'Sub-Category Name (Local)', // Mandatory, Alphanumeric (50,0)
    'CDL_BDG_SERVICE_CODE': 'Service Code', // Mandatory, Alphanumeric (20,0)
    'CDL_BDG_SERVICE_NAME': 'Service Name ', // Mandatory, Alphanumeric (150,0)
    'CDL_BDG_SERVICE_LOCAL_NAME': 'Service Name (Local)', // Mandatory, Alphanumeric (150,0)
    'CDL_BDG_TOTAL_COST': 'Total Cost', // Mandatory, Numeric (18,2)
    'CDL_BDG_VAT_AMOUNT': 'VAT Amount', // Mandatory, Numeric (18,2)
}
  
export const BUDGET_MASTER_LABELS = {
    'CDL_BUD_CHARGE_TYPE_ID': 'Charge Type ID', // Mandatory, Numeric (10,0)
    'CDL_BUD_CHARGE_TYPE': 'Charge Type', // Mandatory, Alphanumeric (50,0)
    'CDL_BUD_GROUP_NAME': 'Group Name', // Mandatory, Alphanumeric (50,0)
    'CDL_BUD_CATEGORY_CODE': 'Category Code', // Mandatory, All Characters (50,0)
    'CDL_BUD_CATEGORY_NAME': 'Category Name', // Mandatory, Alphanumeric (50,0)
    'CDL_BUD_CATEGORY_SUB_CODE': 'Category Sub Code', // Mandatory, All Characters (50,0)
    'CDL_BUD_CATEGORY_SUB_NAME': 'Category Sub Name', // Mandatory, Alphanumeric (50,0)
    'CDL_BUD_CATEGORY_SUB_TO_SUB_CODE': 'Category Sub To Sub Code', // Mandatory, All Characters (50,0)
    'CDL_BUD_CATEGORY_SUB_TO_SUB_NAME': 'Category Sub To Sub Name', // Mandatory, Alphanumeric (50,0)
    'CDL_BUD_SERVICE_NAME': 'Service Name', // Mandatory, Alphanumeric (50,0)
    'CDL_BUD_SERVICE_CODE': 'Service Code', // Mandatory, All Characters (50,0)
    'CDL_BUD_PROVISIONAL_BUDGET_CODE': 'Provisional Budget Code', // Mandatory, All Characters (50,0)
}

const MASTER_BUDGET_COMMON_LABELS = {
  CDL_MASTER_BDG_PAGE_TITLE: 'Master Budgets',
  CDL_MASTER_BDG_PAGE_SUBTITLE: 'Create, manage, and review master budget submissions.',
  CDL_MASTER_BDG_LIST_TITLE: 'Saved Master Budgets',
  CDL_MASTER_BDG_NEW_BUTTON: 'New Master Budget',
  CDL_MASTER_BDG_EMPTY_STATE: 'No master budgets recorded yet. Create a new master budget to get started.',
  CDL_MASTER_BDG_TABLE_CHARGE_TYPE: 'Charge Type',
  CDL_MASTER_BDG_TABLE_GROUP_NAME: 'Group Name',
  CDL_MASTER_BDG_TABLE_PROVISIONAL_CODE: 'Provisional Budget Code',
  CDL_MASTER_BDG_TABLE_ACTIONS: 'Actions',
  CDL_MASTER_BDG_STEP_DETAILS: 'Master Budget Details',
  CDL_MASTER_BDG_STEP_DOCUMENTS: 'Documents',
  CDL_MASTER_BDG_STEP_REVIEW: 'Review',
  CDL_MASTER_BDG_SECTION_GENERAL: 'General Information',
  CDL_MASTER_BDG_SECTION_CATEGORIZATION: 'Categorisation',
  CDL_MASTER_BDG_REVIEW_SUMMARY: 'Master Budget Summary',
  CDL_MASTER_BDG_REVIEW_GENERAL: 'General Information',
  CDL_MASTER_BDG_REVIEW_CATEGORIZATION: 'Categorisation',
  CDL_MASTER_BDG_DOC_TITLE: 'Master Budget Documents',
  CDL_MASTER_BDG_DOC_DESCRIPTION:
    'Upload master budget-related documents to support this submission. You can skip this step if documents are not available yet.',
  CDL_MASTER_BDG_DOC_SAVE_HEADING: 'Save master budget details to upload documents.',
  CDL_MASTER_BDG_DOC_SAVE_MESSAGE:
    'Please return to Step 1 and save the master budget before uploading documents.',
} as const

export const MASTER_BUDGET_LABELS = {
  PAGE_TITLE: 'CDL_MASTER_BDG_PAGE_TITLE',
  PAGE_SUBTITLE: 'CDL_MASTER_BDG_PAGE_SUBTITLE',
  LIST: {
    TITLE: 'CDL_MASTER_BDG_LIST_TITLE',
    NEW_BUTTON: 'CDL_MASTER_BDG_NEW_BUTTON',
    EMPTY_STATE: 'CDL_MASTER_BDG_EMPTY_STATE',
    TABLE_HEADERS: {
      CHARGE_TYPE: 'CDL_MASTER_BDG_TABLE_CHARGE_TYPE',
      GROUP_NAME: 'CDL_MASTER_BDG_TABLE_GROUP_NAME',
      PROVISIONAL_CODE: 'CDL_MASTER_BDG_TABLE_PROVISIONAL_CODE',
      ACTIONS: 'CDL_MASTER_BDG_TABLE_ACTIONS',
    },
  },
  STEPS: {
    DETAILS: 'CDL_MASTER_BDG_STEP_DETAILS',
    DOCUMENTS: 'CDL_MASTER_BDG_STEP_DOCUMENTS',
    REVIEW: 'CDL_MASTER_BDG_STEP_REVIEW',
  },
  SECTION_TITLES: {
    GENERAL: 'CDL_MASTER_BDG_SECTION_GENERAL',
    CATEGORIZATION: 'CDL_MASTER_BDG_SECTION_CATEGORIZATION',
  },
  FORM_FIELDS: {
    CHARGE_TYPE_ID: 'CDL_BUD_CHARGE_TYPE_ID',
    CHARGE_TYPE: 'CDL_BUD_CHARGE_TYPE',
    GROUP_NAME: 'CDL_BUD_GROUP_NAME',
    CATEGORY_CODE: 'CDL_BUD_CATEGORY_CODE',
    CATEGORY_NAME: 'CDL_BUD_CATEGORY_NAME',
    CATEGORY_SUB_CODE: 'CDL_BUD_CATEGORY_SUB_CODE',
    CATEGORY_SUB_NAME: 'CDL_BUD_CATEGORY_SUB_NAME',
    CATEGORY_SUB_TO_SUB_CODE: 'CDL_BUD_CATEGORY_SUB_TO_SUB_CODE',
    CATEGORY_SUB_TO_SUB_NAME: 'CDL_BUD_CATEGORY_SUB_TO_SUB_NAME',
    SERVICE_NAME: 'CDL_BUD_SERVICE_NAME',
    SERVICE_CODE: 'CDL_BUD_SERVICE_CODE',
    PROVISIONAL_BUDGET_CODE: 'CDL_BUD_PROVISIONAL_BUDGET_CODE',
  },
  REVIEW: {
    SUMMARY_TITLE: 'CDL_MASTER_BDG_REVIEW_SUMMARY',
    GENERAL_SECTION: 'CDL_MASTER_BDG_REVIEW_GENERAL',
    CATEGORIZATION_SECTION: 'CDL_MASTER_BDG_REVIEW_CATEGORIZATION',
  },
  DOCUMENTS: {
    TITLE: 'CDL_MASTER_BDG_DOC_TITLE',
    DESCRIPTION: 'CDL_MASTER_BDG_DOC_DESCRIPTION',
    SAVE_HEADING: 'CDL_MASTER_BDG_DOC_SAVE_HEADING',
    SAVE_MESSAGE: 'CDL_MASTER_BDG_DOC_SAVE_MESSAGE',
  },
  FALLBACKS: {
    PAGE_TITLE: MASTER_BUDGET_COMMON_LABELS.CDL_MASTER_BDG_PAGE_TITLE,
    PAGE_SUBTITLE: MASTER_BUDGET_COMMON_LABELS.CDL_MASTER_BDG_PAGE_SUBTITLE,
    LIST: {
      TITLE: MASTER_BUDGET_COMMON_LABELS.CDL_MASTER_BDG_LIST_TITLE,
      NEW_BUTTON: MASTER_BUDGET_COMMON_LABELS.CDL_MASTER_BDG_NEW_BUTTON,
      EMPTY_STATE: MASTER_BUDGET_COMMON_LABELS.CDL_MASTER_BDG_EMPTY_STATE,
      TABLE_HEADERS: {
        CHARGE_TYPE: MASTER_BUDGET_COMMON_LABELS.CDL_MASTER_BDG_TABLE_CHARGE_TYPE,
        GROUP_NAME: MASTER_BUDGET_COMMON_LABELS.CDL_MASTER_BDG_TABLE_GROUP_NAME,
        PROVISIONAL_CODE: MASTER_BUDGET_COMMON_LABELS.CDL_MASTER_BDG_TABLE_PROVISIONAL_CODE,
        ACTIONS: MASTER_BUDGET_COMMON_LABELS.CDL_MASTER_BDG_TABLE_ACTIONS,
      },
    },
    STEPS: {
      DETAILS: MASTER_BUDGET_COMMON_LABELS.CDL_MASTER_BDG_STEP_DETAILS,
      DOCUMENTS: MASTER_BUDGET_COMMON_LABELS.CDL_MASTER_BDG_STEP_DOCUMENTS,
      REVIEW: MASTER_BUDGET_COMMON_LABELS.CDL_MASTER_BDG_STEP_REVIEW,
    },
    SECTION_TITLES: {
      GENERAL: MASTER_BUDGET_COMMON_LABELS.CDL_MASTER_BDG_SECTION_GENERAL,
      CATEGORIZATION: MASTER_BUDGET_COMMON_LABELS.CDL_MASTER_BDG_SECTION_CATEGORIZATION,
    },
    FORM_FIELDS: {
      CHARGE_TYPE_ID: BUDGET_MASTER_LABELS.CDL_BUD_CHARGE_TYPE_ID,
      CHARGE_TYPE: BUDGET_MASTER_LABELS.CDL_BUD_CHARGE_TYPE,
      GROUP_NAME: BUDGET_MASTER_LABELS.CDL_BUD_GROUP_NAME,
      CATEGORY_CODE: BUDGET_MASTER_LABELS.CDL_BUD_CATEGORY_CODE,
      CATEGORY_NAME: BUDGET_MASTER_LABELS.CDL_BUD_CATEGORY_NAME,
      CATEGORY_SUB_CODE: BUDGET_MASTER_LABELS.CDL_BUD_CATEGORY_SUB_CODE,
      CATEGORY_SUB_NAME: BUDGET_MASTER_LABELS.CDL_BUD_CATEGORY_SUB_NAME,
      CATEGORY_SUB_TO_SUB_CODE: BUDGET_MASTER_LABELS.CDL_BUD_CATEGORY_SUB_TO_SUB_CODE,
      CATEGORY_SUB_TO_SUB_NAME: BUDGET_MASTER_LABELS.CDL_BUD_CATEGORY_SUB_TO_SUB_NAME,
      SERVICE_NAME: BUDGET_MASTER_LABELS.CDL_BUD_SERVICE_NAME,
      SERVICE_CODE: BUDGET_MASTER_LABELS.CDL_BUD_SERVICE_CODE,
      PROVISIONAL_BUDGET_CODE: BUDGET_MASTER_LABELS.CDL_BUD_PROVISIONAL_BUDGET_CODE,
    },
    REVIEW: {
      SUMMARY_TITLE: MASTER_BUDGET_COMMON_LABELS.CDL_MASTER_BDG_REVIEW_SUMMARY,
      GENERAL_SECTION: MASTER_BUDGET_COMMON_LABELS.CDL_MASTER_BDG_REVIEW_GENERAL,
      CATEGORIZATION_SECTION: MASTER_BUDGET_COMMON_LABELS.CDL_MASTER_BDG_REVIEW_CATEGORIZATION,
    },
    DOCUMENTS: {
      TITLE: MASTER_BUDGET_COMMON_LABELS.CDL_MASTER_BDG_DOC_TITLE,
      DESCRIPTION: MASTER_BUDGET_COMMON_LABELS.CDL_MASTER_BDG_DOC_DESCRIPTION,
      SAVE_HEADING: MASTER_BUDGET_COMMON_LABELS.CDL_MASTER_BDG_DOC_SAVE_HEADING,
      SAVE_MESSAGE: MASTER_BUDGET_COMMON_LABELS.CDL_MASTER_BDG_DOC_SAVE_MESSAGE,
    },
  },
} as const
     
export const BUDGET_LABELS = {
  PAGE_TITLE: 'CDL_BDG_PAGE_TITLE',
  PAGE_SUBTITLE: 'CDL_BDG_PAGE_SUBTITLE',
  LIST: {
    TITLE: 'CDL_BDG_LIST_TITLE',
    NEW_BUTTON: 'CDL_BDG_NEW_BUTTON',
    EMPTY_STATE: 'CDL_BDG_EMPTY_STATE',
    TABLE_HEADERS: {
      MANAGEMENT_FIRM: 'CDL_BDG_TABLE_MANAGEMENT_FIRM',
      BUDGET_PERIOD: 'CDL_BDG_TABLE_BUDGET_PERIOD',
      TOTAL_COST: 'CDL_BDG_TABLE_TOTAL_COST',
      ACTIONS: 'CDL_BDG_TABLE_ACTIONS',
    },
  },
  STEPS: {
    DETAILS: 'CDL_BDG_STEP_DETAILS',
    DOCUMENTS: 'CDL_BDG_STEP_DOCUMENTS',
    REVIEW: 'CDL_BDG_STEP_REVIEW',
  },
  SECTION_TITLES: {
    GENERAL: 'CDL_BDG_SECTION_GENERAL',
    SERVICE: 'CDL_BDG_SECTION_SERVICE',
    PERIOD: 'CDL_BDG_SECTION_PERIOD',
    CATEGORIZATION: 'CDL_BDG_SECTION_CATEGORIZATION',
    FINANCIALS: 'CDL_BDG_SECTION_FINANCIALS',
  },
  FORM_FIELDS: {
    MANAGEMENT_FIRM_GROUP_ID: 'CDL_BDG_MANAGEMENT_FIRM_GROUP_ID',
    MANAGEMENT_FIRM_GROUP_NAME: 'CDL_BDG_MANAGEMENT_FIRM_GROUP_NAME',
    MANAGEMENT_FIRM_GROUP_LOCAL_NAME: 'CDL_BDG_MANAGEMENT_FIRM_GROUP_LOCAL_NAME',
    MASTER_COMMUNITY_NAME: 'CDL_BDG_MASTER_COMMUNITY_NAME',
    MASTER_COMMUNITY_LOCAL_NAME: 'CDL_BDG_MASTER_COMMUNITY_LOCAL_NAME',
    MANAGEMENT_COMPANY_ID: 'CDL_BDG_MANAGEMENT_COMPANY_ID',
    MANAGEMENT_COMPANY_NAME: 'CDL_BDG_MANAGEMENT_COMPANY_NAME',
    MANAGEMENT_COMPANY_LOCAL_NAME: 'CDL_BDG_MANAGEMENT_COMPANY_LOCAL_NAME',
    MANAGEMENT_FIRM_MANAGER_EMAIL: 'CDL_BDG_PROPERTY_MANAGER_EMAIL',
    SERVICE_CHARGE_GROUP_ID: 'CDL_BDG_SERVICE_CHARGE_GROUP_ID',
    SERVICE_CHARGE_GROUP_NAME: 'CDL_BDG_SERVICE_CHARGE_GROUP_NAME',
    SERVICE_CHARGE_GROUP_LOCAL_NAME: 'CDL_BDG_SERVICE_CHARGE_GROUP_LOCAL_NAME',
    BUDGET_PERIOD_CODE: 'CDL_BDG_BUDGET_PERIOD_CODE',
    BUDGET_PERIOD_TITLE: 'CDL_BDG_BUDGET_PERIOD_TITLE',
    BUDGET_PERIOD_FROM: 'CDL_BDG_BUDGET_PERIOD_FROM',
    BUDGET_PERIOD_TO: 'CDL_BDG_BUDGET_PERIOD_TO',
    CATEGORY_CODE: 'CDL_BDG_CATEGORY_CODE',
    CATEGORY_NAME: 'CDL_BDG_CATEGORY_NAME',
    CATEGORY_LOCAL_NAME: 'CDL_BDG_CATEGORY_LOCAL_NAME',
    SUB_CATEGORY_CODE: 'CDL_BDG_SUB_CATEGORY_CODE',
    SUB_CATEGORY_NAME: 'CDL_BDG_SUB_CATEGORY_NAME',
    SUB_CATEGORY_LOCAL_NAME: 'CDL_BDG_SUB_CATEGORY_LOCAL_NAME',
    SERVICE_CODE: 'CDL_BDG_SERVICE_CODE',
    SERVICE_NAME: 'CDL_BDG_SERVICE_NAME',
    SERVICE_LOCAL_NAME: 'CDL_BDG_SERVICE_LOCAL_NAME',
    TOTAL_COST: 'CDL_BDG_TOTAL_COST',
    VAT_AMOUNT: 'CDL_BDG_VAT_AMOUNT',
  },
  REVIEW: {
    SUMMARY_TITLE: 'CDL_BDG_REVIEW_SUMMARY',
    GENERAL_SECTION: 'CDL_BDG_REVIEW_GENERAL',
    PERIOD_SECTION: 'CDL_BDG_REVIEW_PERIOD',
    CATEGORIZATION_SECTION: 'CDL_BDG_REVIEW_CATEGORIZATION',
    FINANCIALS_SECTION: 'CDL_BDG_REVIEW_FINANCIALS',
  },
  DOCUMENTS: {
    TITLE: 'CDL_BDG_DOC_TITLE',
    DESCRIPTION: 'CDL_BDG_DOC_DESCRIPTION',
    SAVE_HEADING: 'CDL_BDG_DOC_SAVE_HEADING',
    SAVE_MESSAGE: 'CDL_BDG_DOC_SAVE_MESSAGE',
  },
  FALLBACKS: {
    PAGE_TITLE: BUDGET_COMMON_LABELS.CDL_BDG_PAGE_TITLE,
    PAGE_SUBTITLE: BUDGET_COMMON_LABELS.CDL_BDG_PAGE_SUBTITLE,
    LIST: {
      TITLE: BUDGET_COMMON_LABELS.CDL_BDG_LIST_TITLE,
      NEW_BUTTON: BUDGET_COMMON_LABELS.CDL_BDG_NEW_BUTTON,
      EMPTY_STATE: BUDGET_COMMON_LABELS.CDL_BDG_EMPTY_STATE,
      TABLE_HEADERS: {
        MANAGEMENT_FIRM: BUDGET_COMMON_LABELS.CDL_BDG_TABLE_MANAGEMENT_FIRM,
        BUDGET_PERIOD: BUDGET_COMMON_LABELS.CDL_BDG_TABLE_BUDGET_PERIOD,
        TOTAL_COST: BUDGET_COMMON_LABELS.CDL_BDG_TABLE_TOTAL_COST,
        ACTIONS: BUDGET_COMMON_LABELS.CDL_BDG_TABLE_ACTIONS,
      },
    },
    STEPS: {
      DETAILS: BUDGET_COMMON_LABELS.CDL_BDG_STEP_DETAILS,
      DOCUMENTS: BUDGET_COMMON_LABELS.CDL_BDG_STEP_DOCUMENTS,
      REVIEW: BUDGET_COMMON_LABELS.CDL_BDG_STEP_REVIEW,
    },
    SECTION_TITLES: {
      GENERAL: BUDGET_COMMON_LABELS.CDL_BDG_SECTION_GENERAL,
      SERVICE: BUDGET_COMMON_LABELS.CDL_BDG_SECTION_SERVICE,
      PERIOD: BUDGET_COMMON_LABELS.CDL_BDG_SECTION_PERIOD,
      CATEGORIZATION: BUDGET_COMMON_LABELS.CDL_BDG_SECTION_CATEGORIZATION,
      FINANCIALS: BUDGET_COMMON_LABELS.CDL_BDG_SECTION_FINANCIALS,
    },
    FORM_FIELDS: {
      MANAGEMENT_FIRM_GROUP_ID:
        BUDGET_MANAGEMENT_FIRM_LABELS.CDL_BDG_MANAGEMENT_FIRM_GROUP_ID,
      MANAGEMENT_FIRM_GROUP_NAME:
        BUDGET_MANAGEMENT_FIRM_LABELS.CDL_BDG_MANAGEMENT_FIRM_GROUP_NAME,
      MANAGEMENT_FIRM_GROUP_LOCAL_NAME:
        BUDGET_MANAGEMENT_FIRM_LABELS.CDL_BDG_MANAGEMENT_FIRM_GROUP_LOCAL_NAME,
      MASTER_COMMUNITY_NAME:
        BUDGET_MANAGEMENT_FIRM_LABELS.CDL_BDG_MASTER_COMMUNITY_NAME,
      MASTER_COMMUNITY_LOCAL_NAME:
        BUDGET_MANAGEMENT_FIRM_LABELS.CDL_BDG_MASTER_COMMUNITY_LOCAL_NAME,
      MANAGEMENT_COMPANY_ID:
        BUDGET_MANAGEMENT_FIRM_LABELS.CDL_BDG_MANAGEMENT_COMPANY_ID,
      MANAGEMENT_COMPANY_NAME:
        BUDGET_MANAGEMENT_FIRM_LABELS.CDL_BDG_MANAGEMENT_COMPANY_NAME,
      MANAGEMENT_COMPANY_LOCAL_NAME:
        BUDGET_MANAGEMENT_FIRM_LABELS.CDL_BDG_MANAGEMENT_COMPANY_LOCAL_NAME,
      MANAGEMENT_FIRM_MANAGER_EMAIL:
        BUDGET_MANAGEMENT_FIRM_LABELS.CDL_BDG_PROPERTY_MANAGER_EMAIL,
      SERVICE_CHARGE_GROUP_ID:
        BUDGET_MANAGEMENT_FIRM_LABELS.CDL_BDG_SERVICE_CHARGE_GROUP_ID,
      SERVICE_CHARGE_GROUP_NAME:
        BUDGET_MANAGEMENT_FIRM_LABELS.CDL_BDG_SERVICE_CHARGE_GROUP_NAME,
      SERVICE_CHARGE_GROUP_LOCAL_NAME:
        BUDGET_MANAGEMENT_FIRM_LABELS.CDL_BDG_SERVICE_CHARGE_GROUP_LOCAL_NAME,
      BUDGET_PERIOD_CODE:
        BUDGET_MANAGEMENT_FIRM_LABELS.CDL_BDG_BUDGET_PERIOD_CODE,
      BUDGET_PERIOD_TITLE:
        BUDGET_MANAGEMENT_FIRM_LABELS.CDL_BDG_BUDGET_PERIOD_TITLE,
      BUDGET_PERIOD_FROM:
        BUDGET_MANAGEMENT_FIRM_LABELS.CDL_BDG_BUDGET_PERIOD_FROM,
      BUDGET_PERIOD_TO:
        BUDGET_MANAGEMENT_FIRM_LABELS.CDL_BDG_BUDGET_PERIOD_TO,
      CATEGORY_CODE: BUDGET_MANAGEMENT_FIRM_LABELS.CDL_BDG_CATEGORY_CODE,
      CATEGORY_NAME: BUDGET_MANAGEMENT_FIRM_LABELS.CDL_BDG_CATEGORY_NAME,
      CATEGORY_LOCAL_NAME:
        BUDGET_MANAGEMENT_FIRM_LABELS.CDL_BDG_CATEGORY_LOCAL_NAME,
      SUB_CATEGORY_CODE: BUDGET_MANAGEMENT_FIRM_LABELS.CDL_BDG_SUB_CATEGORY_CODE,
      SUB_CATEGORY_NAME: BUDGET_MANAGEMENT_FIRM_LABELS.CDL_BDG_SUB_CATEGORY_NAME,
      SUB_CATEGORY_LOCAL_NAME:
        BUDGET_MANAGEMENT_FIRM_LABELS.CDL_BDG_SUB_CATEGORY_LOCAL_NAME,
      SERVICE_CODE: BUDGET_MANAGEMENT_FIRM_LABELS.CDL_BDG_SERVICE_CODE,
      SERVICE_NAME: BUDGET_MANAGEMENT_FIRM_LABELS.CDL_BDG_SERVICE_NAME,
      SERVICE_LOCAL_NAME: BUDGET_MANAGEMENT_FIRM_LABELS.CDL_BDG_SERVICE_LOCAL_NAME,
      TOTAL_COST: BUDGET_MANAGEMENT_FIRM_LABELS.CDL_BDG_TOTAL_COST,
      VAT_AMOUNT: BUDGET_MANAGEMENT_FIRM_LABELS.CDL_BDG_VAT_AMOUNT,
    },
    REVIEW: {
      SUMMARY_TITLE: BUDGET_COMMON_LABELS.CDL_BDG_REVIEW_SUMMARY,
      GENERAL_SECTION: BUDGET_COMMON_LABELS.CDL_BDG_REVIEW_GENERAL,
      PERIOD_SECTION: BUDGET_COMMON_LABELS.CDL_BDG_REVIEW_PERIOD,
      CATEGORIZATION_SECTION: BUDGET_COMMON_LABELS.CDL_BDG_REVIEW_CATEGORIZATION,
      FINANCIALS_SECTION: BUDGET_COMMON_LABELS.CDL_BDG_REVIEW_FINANCIALS,
    },
    DOCUMENTS: {
      TITLE: BUDGET_COMMON_LABELS.CDL_BDG_DOC_TITLE,
      DESCRIPTION: BUDGET_COMMON_LABELS.CDL_BDG_DOC_DESCRIPTION,
      SAVE_HEADING: BUDGET_COMMON_LABELS.CDL_BDG_DOC_SAVE_HEADING,
      SAVE_MESSAGE: BUDGET_COMMON_LABELS.CDL_BDG_DOC_SAVE_MESSAGE,
    },
  },
} as const

export const getLabelByConfigId = (configId: string) => {
  return (
    BUDGET_COMMON_LABELS[configId as keyof typeof BUDGET_COMMON_LABELS] ||
    MASTER_BUDGET_COMMON_LABELS[configId as keyof typeof MASTER_BUDGET_COMMON_LABELS] ||
    BUDGET_MASTER_LABELS[configId as keyof typeof BUDGET_MASTER_LABELS] ||
    BUDGET_MANAGEMENT_FIRM_LABELS[
      configId as keyof typeof BUDGET_MANAGEMENT_FIRM_LABELS
    ] ||
    configId
  )
}

export const getBudgetLabels = (configId: string) => getLabelByConfigId(configId)
  